name: DegenDuel CI/CD

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    name: Test Suite
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
      
    - name: Run type checking
      run: npm run type-check
      
    - name: Run tests
      run: npm test
      
    - name: Generate coverage report
      run: npm test -- --coverage
      
    - name: Upload coverage reports
      uses: codecov/codecov-action@v3
      with:
        directory: ./coverage/
        fail_ci_if_error: true

  build-dev:
    name: Development Build
    needs: test
    runs-on: ubuntu-latest
    environment: development
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
      
    - name: Build development version
      run: npm run build:dev
      
    - name: Verify build output
      run: |
        if [ -d "dist-dev" ] && [ "$(find dist-dev -type f | wc -l)" -gt 0 ]; then
          echo "✅ Development build successful!"
        else
          echo "❌ Development build failed!"
          exit 1
        fi
        
    - name: Upload development build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: dist-dev
        path: dist-dev
        retention-days: 7

  build-prod:
    name: Production Build
    needs: test
    runs-on: ubuntu-latest
    environment: production
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
      
    - name: Build production version
      run: npm run build:prod
      
    - name: Verify build output
      run: |
        if [ -d "dist" ] && [ "$(find dist -type f | wc -l)" -gt 0 ]; then
          echo "✅ Production build successful!"
        else
          echo "❌ Production build failed!"
          exit 1
        fi
        
    - name: Upload production build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: dist-prod
        path: dist
        retention-days: 7